var header =    '<main class="main">'
+                   '<header class="header">'
+                       '<div class="center">'
+                           '<h1 class="derGiu">DerGiu</h1>'
+                           '<div class="toggle-button-cover">'
+                               '<div class="button r" id="button-9">'
+                                   '<input type="checkbox" class="checkbox" name="DarkModeToggle" id="DarkModeToggle">'
+                                       '<div class="knobs">'
+                                           '<span></span>'
+                                       '</div>'
+                                       '<div class="layer"></div>'
+                               '</div>'
+                           '</div>'
+                       '</div>'
+                       '<nav class="navigationalButton">'
+                           '<a class="a" href="index.html">Home del sito</a>'
+                           '<a class="a" href="Studi.html">Studi</a>'
+                           '<a class="a" href="Progetti.html">Progetti</a>'
+                       '</nav>'
+                   '</header>'
+               '</main>';