var jsonInfo = '['
+        '{"Anno" : "20 Dicembre 2022", "Titolo" : "Progetto TopSecret", "Descrizione" : "Beh diciamo che la passione per arduino e la realizzazione di una casa IOT autonoma, mi hanno portato a navigare in lungo e in largo per il web. Ho trovato e provato progetti prettamente open source, ma nessuno mi ha soddisfatto.  Con questo progetto punto non solo a scollegare i device dal cloud prioritario dell’azienda come fa HomeAssistant, ma andare a distribuire e dividere in layer ogni singola componente direttamente su Arduino senza passare per dei computer"},'
+        '{"Anno" : "10 Agosto 2022", "Titolo" : "Rete Casa", "Descrizione" : "Una fortuna dalla mia parte. Con i lavori di efficentamento energetico con gli incentivi statali ristrutturiamo esternamente casa. Nel rifare la facciata in accordo con la ditta (DCM COSTRUZIONI SRLS di Eboli), concordiamo sul passaggio dei corrugati da una sala che sarà resa server a tutta la casa. La rete progettata è costituita da cavi cat6 fino a 10gbps, Vlan per la divisione delle varie reti, router openwrt e altre componenti di livello aziendale."},'
+        '{"Anno" : "5 Ottobre 2022", "Titolo" : "Università- 3GTech", "Descrizione" : "Progetto creato insieme ad un gruppo universitario, per l’esame di Tecnologie Software per il Web(TSW). Si tratta di un sito web creato utilizzando l’ide Eclipse con il server TOMCAT. La collaborazione del nostro gruppo per arrivare alla creazione del sito è stata davvero interessante a tal punto da creare una forte amicizia."},'
+        '{"Anno" : "5 Novembre 2020", "Titolo" : "BotUnisa", "Descrizione" : "Primo anno di università, iniziato e continuato completamente a distanza. Purtroppo non socializzo con i colleghi poiché a distanza non riesco a socializzare. In pratica mi si ripresento lo stesso problema che ebbi alle superiori con gli avvisi pubblicati solo sul sito web Del dipartimento di informatica. Risolsi prendendo il codice del HackSitoScolastico e cambiando l’url del sito in modo tale da farmi mandare gli avvisi su telegram solo a me."},'
+        '{"Anno" : "18 Novembre 2021", "Titolo" : "CiotolaCroccantiniSmart", "Descrizione" : "Abbandonarono una cagnolina nel mio quartiere e si ritrovò sulla terrazza di mio nonno. C’è ne prendemmo cura e siccome nonno non aveva abbastanza spazio decidemmo di portarla a casa nostra in quanto ha a dispozione un bel po di spazio. Unico problema che oltre lei da anni abbiamo un cane di zona che entra quando piove o per mangiare. Siccome capita che per scuola, università e lavoro non stiamo tutto il giorno a casa e magari il cane di zona entrava. La nostra cagnolina rimaneva senza croccantini. Cosi sapendo che sono microcippati decisi di costruire una ciotola che riesca a leggere il microchip e in base al codice letto apriva una ciotola piuttosto che un’altra. "},'
+        '{"Anno" : "15 Novembre 2021", "Titolo" : "Rfid134 Libreria", "Descrizione" : "Siccome comprai la componente che legge il microchip dalla Cina, essa non aveva delle librerie per utilizzarla ma un solo pdf con le caratteristiche di cosa restituiva la scheda una volta letto il microchip e poi la conversione per leggere il codice non veniva fatta. Online trovai una libreria ma che non si capiva per come era stata strutturata. Così realizzai la mia libreria in modo tale da poter leggere e convertire i valori restituiti dalla scheda"},'
+        '{"Anno" : "17 Febbraio 2020", "Titolo" : "HackSitoScolastico", "Descrizione" : "okok fermi non correte. Si avete letto bene e non si tratta di Hackeraggio del sito scolastico. In pratica l’istituto faceva uscire le circolari esclusivamente all’interno del sito web. Io puntualmente le perdevo perche mi dimenticavo di andare a vedere. Decisi di costruire un bot telegram che faceva il web scraping del sito web, si costruiva ricostruiva l’url del documento pdf e lo mandava sul bot alle sole personi che si erano registarti al bot. Il tutto in maniera anonima perche non salvavo i dati di nessuno ma solo id telegram fatto apposta per i bot. Dopo le prime release aperte solo al me e al docente, e dopo un po’ di miglioramenti e aggiunta di feature, lo aprimmo al solo gruppo Multiskills con un’ottima risultato in quanto funzionava perfettamente anche con una 20 di persone registrate. Ps: hack per me significa Aggiunta. infatti HackSitoScolastico -> AggiuntaAlSitoScolastico"},'
+        '{"Anno" : "20 Ottobre 2019", "Titolo" : "Multiskills - OpenRobyNonVedenti", "Descrizione" : "Con il gruppo multiskills realizzammo OpenRoby un robottino che camminava su una scacchiera. Una versione fisica di CodyMaze un progetto della CodyWeek realizzata dall’università di Urbino. Ci venne l’idea di convertire questo progetto fatto per persone normo dotate a delle persone che purtroppo non possono vedere. Mi venne l’idea di costruire delle card in ferro con il linguaggio delle persone non vedenti e che riuscissero a capire dove l’utente si trovava. Nel caso in cui non rispettava cio che diceva la card veniva emesso un suono in modo tale da far tornare l’utente sulla casella precedente. Purtroppo il Lock-Down non fece procedere il progetto a livello costruttivo, poiché in piena pandemia il software lo completai"},'
+        '{"Anno" : "19 Settembre 2019","Titolo" : "Multiskills - Indice Gulpease", "Descrizione" : "In occasione di non ricordo cosa, la professoressa di Italiano dell’altra classe (ma che partecipava agli Incontri di multiskills), insieme al docente di Multiskills mi chiesero di creare un programmino che andasse ad analizzare l’indice di gulpease di un testo. In pratica questo indice restituisce un valore compreso tra 0 e 100 ed è il valore di leggibilità di un testo. Scrissi il programmino in python perché essendo un indice per la leggibilità del testo ed essendo che il codice dovevo commentarlo alle varie classi, python è sicuramente molto più leggibile ed era adatto allo scopo. Ovviamente non conoscevo python, quindi ci persi un paio di ore a prenderci mano, poi andai liscio."},'
+        '{"Anno" : "15 Settembre 2019","Titolo" : "Multiskills - Slider 3D", "Descrizione" : "Ebbi l’idea di questo progetto poiché dovevamo virtualizzare il nostro istituto e l’istituto Agrario associato a noi. Nel riportare l’istituto agrario ci stavamo mettendo troppo tempo poiché gli attrezzi agricoli da collezione sono tanti. Decisi di ottimizzare i tempi andando a creare uno slider composti da 3 raspberry ognuno con una fotocamera montati su 3 slider montati su un’asta. Ogni raspberry riceveva un comando in ssh che gli faceva scattare una foto e con scp copiata sul computer che eseguiva il programma. E una volta fatta la foto il raspberry veniva spostato di tot cm in altezza e riprendeva il ciclo delle foto. Il mio programma oltre a mandare i comandi in ssh e scp, comunicava sempre tramite Wi-Fi con un arduino che gestiva lo spostamento dei raspberry sullo slider. Una volta catturate tutte le foto le ordinava e le mandava su un programma che analizzava le foto e creava una nuvola di punti dell’oggetto scannerizzato. Non era la cosa più precisa del mondo perché per questo esistono delle attrezzature apposite, ma per quello che ci serviva era ottimo. Il tutto fu costruito ma purtroppo non lo utilizzammo poiché non avevamo tempo a disposizione"},'
+        '{"Anno" : "12 Settembre 2019","Titolo" : "Karaoke", "Descrizione" : "Mi chiesere di scaricare delle canzoni per un software di karaoke. Trovai un sito che ne conteneva tantissime, unica pecca dovevi cliccare su ognuna di essa per farla scaricare. Dopo le prime 20 dissi basta e iniziai a pensare. Realizzai un programmino realizzato in C# che grazie alla tecnica di WebScraping ogni tot secondi cliccava su un link e mi scaricava la musica. Così facendo automatizzai il tutto avendo le canzoni scaricate ma senza dover perdere tempo dietro al sito"},'
+        '{"Anno" : "13 Marzo 2018", "Titolo" : "Casa IOT", "Descrizione" : "Cercando in rete trovai un progettino open source con appena 2 anni di età e volevo provarlo. Sto parlando di Home Assistant versione 0.65.6. Un bellissimo progetto che ancora oggi utilizzo e che mi permette di controllare casa. Iniziai cosi la conquistista di casa convertendola in IOT."},'
+        '{"Anno" : "11 Novembre 2015", "Titolo" : "Sistema solare illuminato","Descrizione" : "La classe elementare di mia sorella ex 5B, realizzó un progettino che riguardava la creazione del sistema solare su una base di polistirolo con i vari pianeti sollevati dal piano con degli stuzzicadenti. Mi chiesero di far illuminare il sistema solare. Grazie all‘utilizzo di un arduino nano ed il saldatore, collegai dei led dentro ogni pianeta creando un programmino che accendeva i pianeti in modo particolare"}'
+    ']';

var timeline = '<ul class="timeline">';
jsonInfo = JSON.parse(jsonInfo);
for (var i = 0; i < jsonInfo.length; i++) {
    timeline += '<li class="timeline-event">'
                + '<h2 class="timeline-event-icon"></h2>'
                + '<div class="timeline-event-copy">'
                    + '<h2 class="timeline-event-thumbnail">' + jsonInfo[i].Anno + '</h2>'
                    + '<h1 class="anno">' + jsonInfo[i].Titolo + '</h1><br>'
                    + '<h3 class="descrizioneTemporale">' + jsonInfo[i].Descrizione + '</h3>'
                + '</div>'
           + '</li>';
}
timeline += '</ul>';




